# Generated by Django 4.2.2 on 2023-06-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=100)),
                ('owner_id', models.CharField(max_length=100)),
                ('templates', models.JSONField(default=dict)),
                ('member_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'bot_server',
            },
        ),
    ]
